spring:
  application:
    name: Mongo DB Example
  data: 
    mongodb:
      host: localhost
      port: 27017
      database: mongo
      repositories:
        enabled: true

server:
  port: 8065

dbProps:
  host: localhost
  port: 27017
  name: mongo
  
com:
  mycompany:
    constraints:
      CheckCase:
        message: MyMessage
